workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      java: 1.8
    cache:
      cache_paths:
        - ~/.gradle/caches[^2^][2]
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          ./gradlew dependencies
      - name: Build APK
        script: |
          ./gradlew assembleRelease artifacts:[^3^][3]
      - build/**/outputs/**/*.apk[^4^][4][^5^][5]
    publishing:
      email:
        recipients:
          - your-email@example.com
