workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      java: 1.8
    cache:
      cache_paths:
        - ~/.gradle/caches
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Set execute permissions for gradlew
        script: |
          chmod +x ./gradlew
      - name: Install dependencies
        script: |
          ./gradlew dependencies
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - fernandoaestrella@gmail.com
